name = "mha-explorer"
main = "worker.js"
compatibility_date = "2026-09-11"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = true

[vars]
FB_API_KEY = "AIzaSyBJTd25x7MKfcQVzAH7ZNNaAwUjXs_-CoI"
FB_EMAIL = "worker@mha-explorer.local"
